package divinerpg.entities.twilight.archer;

import com.mojang.blaze3d.platform.GlStateManager;
import divinerpg.entities.base.render.DivineModel;
import net.minecraft.client.renderer.entity.model.IHasArm;
import net.minecraft.client.renderer.entity.model.RendererModel;
import net.minecraft.entity.MobEntity;
import net.minecraft.util.HandSide;
import net.minecraft.util.math.MathHelper;

public class ArcherModel extends DivineModel<MobEntity> implements IHasArm {
    RendererModel head;
    RendererModel body1;
    RendererModel rightarmext;
    RendererModel leftfoot;
    RendererModel bodymain;
    RendererModel body2;
    RendererModel body3;
    RendererModel body4;
    RendererModel body6;
    RendererModel body5;
    RendererModel rightarm;
    RendererModel rightarmcap;
    RendererModel leftarm;
    RendererModel leftarmext;
    RendererModel leftleg;
    RendererModel leftarmcap;
    RendererModel leftlegcap;
    RendererModel rightfoot;
    RendererModel rightleg;
    RendererModel rightlegcap;
    RendererModel Shape1;
    RendererModel Shape2;
    RendererModel Shape3;
    RendererModel Shape4;
    RendererModel Shape5;
    RendererModel Shape6;
    RendererModel Shape7;
    RendererModel Shape8;
    RendererModel Shape9;
    RendererModel Shape10;
    RendererModel Shape11;
    RendererModel Shape12;
    RendererModel Shape13;
    RendererModel Shape14;
    RendererModel Shape15;
    RendererModel Shape16;
    RendererModel Shape17;
    RendererModel Shape18;
    RendererModel Shape19;
    RendererModel Shape20;

    public ArcherModel() {
        textureWidth = 64;
        textureHeight = 32;

        head = new RendererModel(this, 0, 0);
        head.addBox(-4F, -8F, -4F, 8, 8, 8);
        head.setRotationPoint(0F, -16F, -19F);
        head.setTextureSize(64, 32);
        head.mirror = true;
        setRotation(head, 0F, 0F, 0F);
        body1 = new RendererModel(this, 0, 22);
        body1.addBox(-4F, 0F, -2F, 8, 6, 4);
        body1.setRotationPoint(0F, -12F, -2F);
        body1.setTextureSize(64, 32);
        body1.mirror = true;
        setRotation(body1, 0.2617994F, 0F, 0F);
        rightarmext = new RendererModel(this, 40, 10);
        rightarmext.addBox(-7F, -2F, -2F, 8, 4, 4);
        rightarmext.setRotationPoint(-5F, -16F, -6F);
        rightarmext.setTextureSize(64, 32);
        rightarmext.mirror = true;
        setRotation(rightarmext, 0F, 0F, 0F);
        leftfoot = new RendererModel(this, 28, 15);
        leftfoot.addBox(-3F, 17F, -9F, 6, 5, 12);
        leftfoot.setRotationPoint(10F, 2F, 0F);
        leftfoot.setTextureSize(64, 32);
        leftfoot.mirror = true;
        setRotation(leftfoot, 0F, 0F, 0F);
        bodymain = new RendererModel(this, 28, 10);
        bodymain.addBox(-4F, 0F, -2F, 14, 18, 4);
        bodymain.setRotationPoint(-3F, -6F, 0F);
        bodymain.setTextureSize(64, 32);
        bodymain.mirror = true;
        setRotation(bodymain, 0F, 0F, 0F);
        body2 = new RendererModel(this, 0, 22);
        body2.addBox(-4F, 0F, -2F, 8, 6, 4);
        body2.setRotationPoint(0F, -21F, -14F);
        body2.setTextureSize(64, 32);
        body2.mirror = true;
        setRotation(body2, 1.308997F, 0F, 0F);
        body3 = new RendererModel(this, 16, 16);
        body3.addBox(-4F, 0F, -2F, 4, 3, 4);
        body3.setRotationPoint(2F, -21F, -16F);
        body3.setTextureSize(64, 32);
        body3.mirror = true;
        setRotation(body3, 1.570796F, 0F, 0F);
        body4 = new RendererModel(this, 0, 22);
        body4.addBox(-4F, 0F, -2F, 4, 3, 4);
        body4.setRotationPoint(2F, -14F, -3F);
        body4.setTextureSize(64, 32);
        body4.mirror = true;
        setRotation(body4, 0.5235988F, 0F, 0F);
        body6 = new RendererModel(this, 0, 22);
        body6.addBox(-4F, 0F, -2F, 8, 6, 4);
        body6.setRotationPoint(0F, -18F, -7F);
        body6.setTextureSize(64, 32);
        body6.mirror = true;
        setRotation(body6, 0.7853982F, 0F, 0F);
        body5 = new RendererModel(this, 0, 22);
        body5.addBox(-4F, 0F, -2F, 4, 3, 4);
        body5.setRotationPoint(2F, -19F, -9F);
        body5.setTextureSize(64, 32);
        body5.mirror = true;
        setRotation(body5, 1.047198F, 0F, 0F);
        rightarm = new RendererModel(this, 40, 10);
        rightarm.addBox(-11F, -2F, -2F, 4, 18, 4);
        rightarm.setRotationPoint(-5F, -16F, -6F);
        rightarm.setTextureSize(64, 32);
        rightarm.mirror = true;
        setRotation(rightarm, 0F, 0F, 0F);
        rightarmcap = new RendererModel(this, 40, 10);
        rightarmcap.addBox(-12F, -3F, -3F, 6, 6, 6);
        rightarmcap.setRotationPoint(-5F, -16F, -6F);
        rightarmcap.setTextureSize(64, 32);
        rightarmcap.mirror = true;
        setRotation(rightarmcap, 0F, 0F, 0F);
        leftarm = new RendererModel(this, 40, 10);
        leftarm.addBox(7F, -2F, -2F, 4, 18, 4);
        leftarm.setRotationPoint(5F, -16F, -6F);
        leftarm.setTextureSize(64, 32);
        leftarm.mirror = true;
        setRotation(leftarm, 0F, 0F, 0F);
        leftarmext = new RendererModel(this, 40, 10);
        leftarmext.addBox(-1F, -2F, -2F, 8, 4, 4);
        leftarmext.setRotationPoint(5F, -16F, -6F);
        leftarmext.setTextureSize(64, 32);
        leftarmext.mirror = true;
        setRotation(leftarmext, 0F, 0F, 0F);
        leftarmcap = new RendererModel(this, 40, 10);
        leftarmcap.addBox(6F, -3F, -3F, 6, 6, 6);
        leftarmcap.setRotationPoint(5F, -16F, -6F);
        leftarmcap.setTextureSize(64, 32);
        leftarmcap.mirror = true;
        setRotation(leftarmcap, 0F, 0F, 0F);
        leftleg = new RendererModel(this, 37, 6);
        leftleg.addBox(-2F, 0F, -2F, 4, 22, 4);
        leftleg.setRotationPoint(10F, 2F, 0F);
        leftleg.setTextureSize(64, 32);
        leftleg.mirror = true;
        setRotation(leftleg, 0F, 0F, 0F);
        leftlegcap = new RendererModel(this, 37, 6);
        leftlegcap.addBox(-3F, -2F, -3F, 6, 5, 6);
        leftlegcap.setRotationPoint(10F, 2F, 0F);
        leftlegcap.setTextureSize(64, 32);
        leftlegcap.mirror = true;
        setRotation(leftlegcap, 0F, 0F, 0F);
        rightfoot = new RendererModel(this, 28, 15);
        rightfoot.addBox(-3F, 17F, -9F, 6, 5, 12);
        rightfoot.setRotationPoint(-10F, 2F, 0F);
        rightfoot.setTextureSize(64, 32);
        rightfoot.mirror = true;
        setRotation(rightfoot, 0F, 0F, 0F);
        rightleg = new RendererModel(this, 37, 6);
        rightleg.addBox(-2F, 0F, -2F, 4, 22, 4);
        rightleg.setRotationPoint(-10F, 2F, 0F);
        rightleg.setTextureSize(64, 32);
        rightleg.mirror = true;
        setRotation(rightleg, 0F, 0F, 0F);
        rightlegcap = new RendererModel(this, 37, 6);
        rightlegcap.addBox(-3F, -2F, -3F, 6, 5, 6);
        rightlegcap.setRotationPoint(-10F, 2F, 0F);
        rightlegcap.setTextureSize(64, 32);
        rightlegcap.mirror = true;
        setRotation(rightlegcap, 0F, 0F, 0F);
        Shape1 = new RendererModel(this, 35, 14);
        Shape1.addBox(0F, 0F, 0F, 4, 9, 1);
        Shape1.setRotationPoint(-2F, -31F, -13F);
        Shape1.setTextureSize(64, 32);
        Shape1.mirror = true;
        setRotation(Shape1, 0F, 0F, 0F);
        Shape2 = new RendererModel(this, 35, 14);
        Shape2.addBox(0F, 0F, 0F, 4, 9, 1);
        Shape2.setRotationPoint(-2F, -29F, -11F);
        Shape2.setTextureSize(64, 32);
        Shape2.mirror = true;
        setRotation(Shape2, 0F, 0F, 0F);
        Shape3 = new RendererModel(this, 35, 14);
        Shape3.addBox(0F, 0F, 0F, 4, 9, 1);
        Shape3.setRotationPoint(-2F, -27F, -9F);
        Shape3.setTextureSize(64, 32);
        Shape3.mirror = true;
        setRotation(Shape3, 0F, 0F, 0F);
        Shape4 = new RendererModel(this, 35, 14);
        Shape4.addBox(0F, 0F, 0F, 4, 9, 1);
        Shape4.setRotationPoint(-2F, -8F, 8F);
        Shape4.setTextureSize(64, 32);
        Shape4.mirror = true;
        setRotation(Shape4, -1.047198F, 0F, 0F);
        Shape5 = new RendererModel(this, 35, 14);
        Shape5.addBox(0F, 0F, 0F, 4, 9, 1);
        Shape5.setRotationPoint(-2F, -5F, 10F);
        Shape5.setTextureSize(64, 32);
        Shape5.mirror = true;
        setRotation(Shape5, -1.308997F, 0F, 0F);
        Shape6 = new RendererModel(this, 35, 14);
        Shape6.addBox(0F, 0F, 0F, 4, 9, 1);
        Shape6.setRotationPoint(-2F, -24F, -2F);
        Shape6.setTextureSize(64, 32);
        Shape6.mirror = true;
        setRotation(Shape6, -0.2617994F, 0F, 0F);
        Shape7 = new RendererModel(this, 35, 14);
        Shape7.addBox(0F, 0F, 0F, 4, 9, 1);
        Shape7.setRotationPoint(-2F, -25F, -4F);
        Shape7.setTextureSize(64, 32);
        Shape7.mirror = true;
        setRotation(Shape7, -0.2617994F, 0F, 0F);
        Shape8 = new RendererModel(this, 35, 14);
        Shape8.addBox(1F, 0F, 0F, 2, 9, 1);
        Shape8.setRotationPoint(-2F, -20F, 3F);
        Shape8.setTextureSize(64, 32);
        Shape8.mirror = true;
        setRotation(Shape8, -0.5235988F, 0F, 0F);
        Shape9 = new RendererModel(this, 35, 14);
        Shape9.addBox(0F, 0F, 0F, 4, 9, 1);
        Shape9.setRotationPoint(-2F, -12F, 7F);
        Shape9.setTextureSize(64, 32);
        Shape9.mirror = true;
        setRotation(Shape9, -0.7853982F, 0F, 0F);
        Shape10 = new RendererModel(this, 35, 14);
        Shape10.addBox(0F, 0F, 0F, 4, 9, 1);
        Shape10.setRotationPoint(-2F, -15F, 6F);
        Shape10.setTextureSize(64, 32);
        Shape10.mirror = true;
        setRotation(Shape10, -0.7853982F, 0F, 0F);
        Shape11 = new RendererModel(this, 35, 14);
        Shape11.addBox(0F, 0F, 0F, 2, 9, 1);
        Shape11.setRotationPoint(-1F, -18F, 5F);
        Shape11.setTextureSize(64, 32);
        Shape11.mirror = true;
        setRotation(Shape11, -0.7853982F, 0F, 0F);
        Shape12 = new RendererModel(this, 35, 14);
        Shape12.addBox(0F, 0F, 0F, 4, 9, 1);
        Shape12.setRotationPoint(-2F, 10F, 10F);
        Shape12.setTextureSize(64, 32);
        Shape12.mirror = true;
        setRotation(Shape12, -1.570796F, 0F, 0F);
        Shape13 = new RendererModel(this, 35, 14);
        Shape13.addBox(0F, 0F, 0F, 4, 9, 1);
        Shape13.setRotationPoint(-2F, 8F, 10F);
        Shape13.setTextureSize(64, 32);
        Shape13.mirror = true;
        setRotation(Shape13, -1.570796F, 0F, 0F);
        Shape14 = new RendererModel(this, 35, 14);
        Shape14.addBox(0F, 0F, 0F, 4, 9, 1);
        Shape14.setRotationPoint(-2F, 6F, 10F);
        Shape14.setTextureSize(64, 32);
        Shape14.mirror = true;
        setRotation(Shape14, -1.570796F, 0F, 0F);
        Shape15 = new RendererModel(this, 35, 14);
        Shape15.addBox(0F, 0F, 0F, 4, 9, 1);
        Shape15.setRotationPoint(-2F, 4F, 10F);
        Shape15.setTextureSize(64, 32);
        Shape15.mirror = true;
        setRotation(Shape15, -1.570796F, 0F, 0F);
        Shape16 = new RendererModel(this, 35, 14);
        Shape16.addBox(0F, 0F, 0F, 4, 9, 1);
        Shape16.setRotationPoint(-2F, 2F, 10F);
        Shape16.setTextureSize(64, 32);
        Shape16.mirror = true;
        setRotation(Shape16, -1.570796F, 0F, 0F);
        Shape17 = new RendererModel(this, 35, 14);
        Shape17.addBox(0F, 0F, 0F, 4, 9, 1);
        Shape17.setRotationPoint(-2F, 0F, 10F);
        Shape17.setTextureSize(64, 32);
        Shape17.mirror = true;
        setRotation(Shape17, -1.570796F, 0F, 0F);
        Shape18 = new RendererModel(this, 35, 14);
        Shape18.addBox(0F, 0F, 0F, 4, 9, 1);
        Shape18.setRotationPoint(-2F, -2F, 10F);
        Shape18.setTextureSize(64, 32);
        Shape18.mirror = true;
        setRotation(Shape18, -1.570796F, 0F, 0F);
        Shape19 = new RendererModel(this, 35, 14);
        Shape19.addBox(1F, 0F, 0F, 2, 9, 1);
        Shape19.setRotationPoint(-2F, -26F, -6F);
        Shape19.setTextureSize(64, 32);
        Shape19.mirror = true;
        setRotation(Shape19, -0.2617994F, 0F, 0F);
        Shape20 = new RendererModel(this, 35, 14);
        Shape20.addBox(1F, 0F, 0F, 2, 9, 1);
        Shape20.setRotationPoint(-2F, -22F, 1F);
        Shape20.setTextureSize(64, 32);
        Shape20.mirror = true;
        setRotation(Shape20, -0.5235988F, 0F, 0F);
    }

    @Override
    public void postRenderArm(float scale, HandSide side) {
        rightarm.postRender(scale);

        GlStateManager.translatef(-0.0625F, 0, 0.0625F);
        GlStateManager.translatef(-0.45F, 0.35F, -0.05F);
    }

    @Override
    public void setRotationAngles(MobEntity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor) {
        super.setRotationAngles(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scaleFactor);

        this.head.rotateAngleY = netHeadYaw / (180F / (float) Math.PI);
        this.head.rotateAngleX = headPitch / (180F / (float) Math.PI);

        this.rightarm.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F + (float) Math.PI) * 2.0F * limbSwingAmount * 0.5F;
        this.rightarmcap.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F + (float) Math.PI) * 2.0F * limbSwingAmount * 0.5F;
        this.rightarmext.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F + (float) Math.PI) * 2.0F * limbSwingAmount * 0.5F;

        this.leftarm.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F) * 2.0F * limbSwingAmount * 0.5F;
        this.leftarmcap.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F) * 2.0F * limbSwingAmount * 0.5F;
        this.leftarmext.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F) * 2.0F * limbSwingAmount * 0.5F;

        this.rightarm.rotateAngleZ = 0.0F;
        this.rightarmcap.rotateAngleZ = 0.0F;
        this.rightarmext.rotateAngleZ = 0.0F;

        this.leftarm.rotateAngleZ = 0.0F;
        this.leftarmcap.rotateAngleZ = 0.0F;
        this.leftarmext.rotateAngleZ = 0.0F;

        this.rightleg.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F) * 1.4F * limbSwingAmount;
        this.rightlegcap.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F) * 1.4F * limbSwingAmount;
        this.rightfoot.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F) * 1.4F * limbSwingAmount;

        this.leftleg.rotateAngleX = MathHelper.cos((float) (limbSwing * 0.6662F + Math.PI)) * 1.4F * limbSwingAmount;
        this.leftlegcap.rotateAngleX = MathHelper.cos((float) (limbSwing * 0.6662F + Math.PI)) * 1.4F * limbSwingAmount;
        this.leftfoot.rotateAngleX = MathHelper.cos((float) (limbSwing * 0.6662F + Math.PI)) * 1.4F * limbSwingAmount;

        this.rightleg.rotateAngleY = 0.0F;
        this.rightlegcap.rotateAngleY = 0.0F;
        this.rightfoot.rotateAngleY = 0.0F;

        this.leftleg.rotateAngleY = 0.0F;
        this.leftlegcap.rotateAngleY = 0.0F;
        this.leftfoot.rotateAngleY = 0.0F;

        this.rightarm.rotateAngleY = 0.0F;
        this.rightarmcap.rotateAngleY = 0.0F;
        this.rightarmext.rotateAngleY = 0.0F;

        this.leftarm.rotateAngleY = 0.0F;
        this.leftarmcap.rotateAngleY = 0.0F;
        this.leftarmext.rotateAngleY = 0.0F;

        this.rightarm.rotateAngleZ += MathHelper.cos(ageInTicks * 0.09F) * 0.05F + 0.05F;
        this.rightarmcap.rotateAngleZ += MathHelper.cos(ageInTicks * 0.09F) * 0.05F + 0.05F;
        this.rightarmext.rotateAngleZ += MathHelper.cos(ageInTicks * 0.09F) * 0.05F + 0.05F;

        this.leftarm.rotateAngleZ -= MathHelper.cos(ageInTicks * 0.09F) * 0.05F + 0.05F;
        this.leftarmcap.rotateAngleZ -= MathHelper.cos(ageInTicks * 0.09F) * 0.05F + 0.05F;
        this.leftarmext.rotateAngleZ -= MathHelper.cos(ageInTicks * 0.09F) * 0.05F + 0.05F;

        this.rightarm.rotateAngleX += MathHelper.sin(ageInTicks * 0.067F) * 0.05F;
        this.rightarmcap.rotateAngleX += MathHelper.sin(ageInTicks * 0.067F) * 0.05F;
        this.rightarmext.rotateAngleX += MathHelper.sin(ageInTicks * 0.067F) * 0.05F;

        this.leftarm.rotateAngleX -= MathHelper.sin(ageInTicks * 0.067F) * 0.05F;
        this.leftarmcap.rotateAngleX -= MathHelper.sin(ageInTicks * 0.067F) * 0.05F;
        this.leftarmext.rotateAngleX -= MathHelper.sin(ageInTicks * 0.067F) * 0.05F;
    }
}
