package divinerpg.entities.twilight.tomo;

import divinerpg.entities.base.render.DivineModel;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.entity.MobEntity;

public class TomoModel extends DivineModel<MobEntity> {
    ModelRenderer body;
    ModelRenderer headtop;
    ModelRenderer headbottom;
    ModelRenderer headright;
    ModelRenderer headleft;
    ModelRenderer hornright;
    ModelRenderer hornleft;
    ModelRenderer sensorright;
    ModelRenderer sensorleft;
    ModelRenderer wingright;
    ModelRenderer wingleft;

    public TomoModel() {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.body = new ModelRenderer(this, 0, 7);
        this.body.func_228300_a_(0.0F, 0.0F, 0.0F, 16, 9, 16);
        this.body.setRotationPoint(8.0F, 10.0F, -8.0F);
        this.body.setTextureSize(64, 32);
        this.body.mirror = true;
        this.setRotation(this.body, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.headtop = new ModelRenderer(this, 15, 14);
        this.headtop.func_228300_a_(0.0F, 0.0F, 0.0F, 2, 2, 16);
        this.headtop.setRotationPoint(8.0F, 10.0F, -10.0F);
        this.headtop.setTextureSize(64, 32);
        this.headtop.mirror = true;
        this.setRotation(this.headtop, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.headbottom = new ModelRenderer(this, 32, 0);
        this.headbottom.func_228300_a_(0.0F, 0.0F, 0.0F, 2, 2, 14);
        this.headbottom.setRotationPoint(7.0F, 16.0F, -10.0F);
        this.headbottom.setTextureSize(64, 32);
        this.headbottom.mirror = true;
        this.setRotation(this.headbottom, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.headright = new ModelRenderer(this, 54, 0);
        this.headright.func_228300_a_(0.0F, 0.0F, 0.0F, 2, 4, 2);
        this.headright.setRotationPoint(7.0F, 12.0F, -10.0F);
        this.headright.setTextureSize(64, 32);
        this.headright.mirror = true;
        this.setRotation(this.headright, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.headleft = new ModelRenderer(this, 54, 0);
        this.headleft.func_228300_a_(0.0F, -1.0F, 0.0F, 2, 4, 2);
        this.headleft.setRotationPoint(-5.0F, 13.0F, -10.0F);
        this.headleft.setTextureSize(64, 32);
        this.headleft.mirror = true;
        this.setRotation(this.headleft, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.hornright = new ModelRenderer(this, 0, 12);
        this.hornright.func_228300_a_(0.0F, 0.0F, 0.0F, 2, 6, 2);
        this.hornright.setRotationPoint(6.0F, 4.0F, -3.0F);
        this.hornright.setTextureSize(64, 32);
        this.hornright.mirror = true;
        this.setRotation(this.hornright, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.hornleft = new ModelRenderer(this, 0, 13);
        this.hornleft.func_228300_a_(0.0F, 0.0F, 0.0F, 2, 6, 2);
        this.hornleft.setRotationPoint(-4.0F, 4.0F, -3.0F);
        this.hornleft.setTextureSize(64, 32);
        this.hornleft.mirror = true;
        this.setRotation(this.hornleft, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.sensorright = new ModelRenderer(this, 0, 20);
        this.sensorright.func_228300_a_(0.0F, 0.0F, 0.0F, 6, 2, 2);
        this.sensorright.setRotationPoint(-4.0F, 4.0F, -9.0F);
        this.sensorright.setTextureSize(64, 32);
        this.sensorright.mirror = true;
        this.setRotation(this.sensorright, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.sensorleft = new ModelRenderer(this, 0, 20);
        this.sensorleft.func_228300_a_(0.0F, 0.0F, 0.0F, 6, 2, 2);
        this.sensorleft.setRotationPoint(6.0F, 4.0F, -9.0F);
        this.sensorleft.setTextureSize(64, 32);
        this.sensorleft.mirror = true;
        this.setRotation(this.sensorleft, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.wingright = new ModelRenderer(this, 27, 0);
        this.wingright.func_228300_a_(0.0F, 0.0F, 0.0F, 10, 2, 8);
        this.wingright.setRotationPoint(-8.0F, 12.0F, -6.0F);
        this.wingright.setTextureSize(64, 32);
        this.wingright.mirror = true;
        this.setRotation(this.wingright, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.wingleft = new ModelRenderer(this, 29, 0);
        this.wingleft.func_228300_a_(0.0F, 0.0F, 0.0F, 10, 2, 8);
        this.wingleft.setRotationPoint(16.0F, 12.0F, -6.0F);
        this.wingleft.setTextureSize(64, 32);
        this.wingleft.mirror = true;
        this.setRotation(this.wingleft, 0.0F, -((float) Math.PI / 2F), 0.0F);
    }
}
