package divinerpg.entities.twilight.tomo;

import divinerpg.entities.base.DivineModel;
import net.minecraft.client.renderer.entity.model.RendererModel;
import net.minecraft.entity.MobEntity;

public class TomoModel extends DivineModel<MobEntity> {
    RendererModel body;
    RendererModel headtop;
    RendererModel headbottom;
    RendererModel headright;
    RendererModel headleft;
    RendererModel hornright;
    RendererModel hornleft;
    RendererModel sensorright;
    RendererModel sensorleft;
    RendererModel wingright;
    RendererModel wingleft;

    public TomoModel() {
        this.textureWidth = 64;
        this.textureHeight = 32;
        this.body = new RendererModel(this, 0, 7);
        this.body.addBox(0.0F, 0.0F, 0.0F, 16, 9, 16);
        this.body.setRotationPoint(8.0F, 10.0F, -8.0F);
        this.body.setTextureSize(64, 32);
        this.body.mirror = true;
        this.setRotation(this.body, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.headtop = new RendererModel(this, 15, 14);
        this.headtop.addBox(0.0F, 0.0F, 0.0F, 2, 2, 16);
        this.headtop.setRotationPoint(8.0F, 10.0F, -10.0F);
        this.headtop.setTextureSize(64, 32);
        this.headtop.mirror = true;
        this.setRotation(this.headtop, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.headbottom = new RendererModel(this, 32, 0);
        this.headbottom.addBox(0.0F, 0.0F, 0.0F, 2, 2, 14);
        this.headbottom.setRotationPoint(7.0F, 16.0F, -10.0F);
        this.headbottom.setTextureSize(64, 32);
        this.headbottom.mirror = true;
        this.setRotation(this.headbottom, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.headright = new RendererModel(this, 54, 0);
        this.headright.addBox(0.0F, 0.0F, 0.0F, 2, 4, 2);
        this.headright.setRotationPoint(7.0F, 12.0F, -10.0F);
        this.headright.setTextureSize(64, 32);
        this.headright.mirror = true;
        this.setRotation(this.headright, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.headleft = new RendererModel(this, 54, 0);
        this.headleft.addBox(0.0F, -1.0F, 0.0F, 2, 4, 2);
        this.headleft.setRotationPoint(-5.0F, 13.0F, -10.0F);
        this.headleft.setTextureSize(64, 32);
        this.headleft.mirror = true;
        this.setRotation(this.headleft, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.hornright = new RendererModel(this, 0, 12);
        this.hornright.addBox(0.0F, 0.0F, 0.0F, 2, 6, 2);
        this.hornright.setRotationPoint(6.0F, 4.0F, -3.0F);
        this.hornright.setTextureSize(64, 32);
        this.hornright.mirror = true;
        this.setRotation(this.hornright, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.hornleft = new RendererModel(this, 0, 13);
        this.hornleft.addBox(0.0F, 0.0F, 0.0F, 2, 6, 2);
        this.hornleft.setRotationPoint(-4.0F, 4.0F, -3.0F);
        this.hornleft.setTextureSize(64, 32);
        this.hornleft.mirror = true;
        this.setRotation(this.hornleft, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.sensorright = new RendererModel(this, 0, 20);
        this.sensorright.addBox(0.0F, 0.0F, 0.0F, 6, 2, 2);
        this.sensorright.setRotationPoint(-4.0F, 4.0F, -9.0F);
        this.sensorright.setTextureSize(64, 32);
        this.sensorright.mirror = true;
        this.setRotation(this.sensorright, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.sensorleft = new RendererModel(this, 0, 20);
        this.sensorleft.addBox(0.0F, 0.0F, 0.0F, 6, 2, 2);
        this.sensorleft.setRotationPoint(6.0F, 4.0F, -9.0F);
        this.sensorleft.setTextureSize(64, 32);
        this.sensorleft.mirror = true;
        this.setRotation(this.sensorleft, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.wingright = new RendererModel(this, 27, 0);
        this.wingright.addBox(0.0F, 0.0F, 0.0F, 10, 2, 8);
        this.wingright.setRotationPoint(-8.0F, 12.0F, -6.0F);
        this.wingright.setTextureSize(64, 32);
        this.wingright.mirror = true;
        this.setRotation(this.wingright, 0.0F, -((float) Math.PI / 2F), 0.0F);
        this.wingleft = new RendererModel(this, 29, 0);
        this.wingleft.addBox(0.0F, 0.0F, 0.0F, 10, 2, 8);
        this.wingleft.setRotationPoint(16.0F, 12.0F, -6.0F);
        this.wingleft.setTextureSize(64, 32);
        this.wingleft.mirror = true;
        this.setRotation(this.wingleft, 0.0F, -((float) Math.PI / 2F), 0.0F);
    }
}
